
name: publish

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python "3.11"
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Install
      run: |
        pip install .
    - name: Run Test
      run: |
         pytest tests
    - name: Build a binary wheel and a source tarball
      run: |
        pip install build
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
